### ISSUE TITLE
printf functions broken

### ISSUE THREAD

**Issue by bojjenclon** [mickjc750/str#6]
Code that I previously wrote (that was working) using the `_append_printf` functions now results in the buffer losing data. I tested manually writing to a buffer using `sprintf` then calling `strbuf_append` and that works, so it seems to be specific to something in the `strbuf_append_printf` call.

**Comment by mickjc750** [comment]
Hi, 

Hmm, it's still working in the test, where I do;
	strbuf_assign(&buf, cstr("Hello"));
	strbuf_append_printf(&buf, " Appending one more number %i", 748921);

By losing data, do you mean the buffer is emptied?
How did you create the buffer?
Could you provide sample strings for me to try out?

The only thing I changed recently, was to add the format checking attribute on line 658 of strbuf.h, you could try removing this and see if it fixes it.

This looks right and works with my test under GCC, but maybe it's breaking with your compiler? do you get any warnings?

**Comment by bojjenclon** [comment]
So I'll try to explain without just dumping a ton of code here:

Basically, I'm writing a serialization process for some input management. My intent is to use the `strbuf_t` as a means of building out the serialized string line by line. To that end, I start with this:

`strbuf_t *buf = strbuf_create(cstr("[input]\n"), NULL);`

I then loop through all of my mapped inputs, and in each loop do something like this:

```
strbuf_append(&buf, "[[input.mapping]]\n");
strbuf_append_printf(&buf, "action = \"%s\"\n", mapping->action);
strbuf_append_printf(&buf, "type = %d\n", mapping->type);
```

I would expect at the end of the loop, `buf` would contain multiple mappings. However, if I do a simple `printf(buf->cstr)` afteward, it only contains some of the data, not all of it. I don't know where the rest of the lines are going.

In the case that I'm testing, the loop runs `32` times and the buffer should have about 4 lines per iteration. I end up with quite a bit less than that. To make sure it wasn't something weird about my data, I also tried just dumping the process to console, and it all appears correct there.

No errors or warnings that I see, although it may be buried somewhere in my cmake setup to be honest.

**Comment by mickjc750** [comment]
Thanks, I have reproduced the problem, I'm on it....

**Comment by mickjc750** [comment]
Got it, see latest commit. Sorry this gave you some grief.

**Comment by bojjenclon** [comment]
Perfect! Thank you for the quick response, really appreciate it, and this library is fantastic! :)
